# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: bychar 3.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "bychar"
  s.version = "3.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Julik Tarkhanov"]
  s.date = "2014-12-10"
  s.description = " Helps parsing IO char by char "
  s.email = "me@julik.nl"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "bychar.gemspec",
    "lib/bychar.rb",
    "lib/impls/reader_bare.rb",
    "lib/impls/reader_iobuf.rb",
    "lib/impls/reader_strbuf.rb",
    "test/helper.rb",
    "test/huge_nuke_tcl.tcl",
    "test/test_ioreader.rb",
    "test/test_reader.rb",
    "test/test_strreader.rb",
    "test/test_z_bench.rb"
  ]
  s.homepage = "http://github.com/julik/bychar"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Helps parsing IO char by char"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<test-unit>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["= 1.8.4"])
      s.add_development_dependency(%q<flexmock>, ["~> 0.8"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<test-unit>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["= 1.8.4"])
      s.add_dependency(%q<flexmock>, ["~> 0.8"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<test-unit>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["= 1.8.4"])
    s.add_dependency(%q<flexmock>, ["~> 0.8"])
  end
end

